---
type: l3spine

# Spine Switches
l3spine:
  defaults:
    platform: cEOS
    spanning_tree_mode: mstp
    spanning_tree_priority: 4096
    loopback_ipv4_pool: 10.2.252.0/24
    mlag_peer_ipv4_pool: 10.2.253.0/31
    mlag_peer_l3_ipv4_pool: 10.2.253.2/31
    virtual_router_mac_address: 00:1c:73:00:dc:01
    mlag_interfaces: [ Ethernet1, Ethernet6 ]
  node_groups:
    - group: SPINES
      nodes:
        - name: s2-spine1
          id: 1
          mgmt_ip: 192.168.0.20/24
        - name: s2-spine2
          id: 2
          mgmt_ip: 192.168.0.21/24
