---
type: leaf

# Leaf Switches
leaf:
  defaults:
    platform: cEOS
    mlag_peer_ipv4_pool: 10.2.253.0/31
    spanning_tree_mode: mstp
    spanning_tree_priority: 16384
    uplink_switches: [ s2-spine1, s2-spine2 ]
    uplink_interfaces: [ Ethernet2, Ethernet3 ]
    mlag_interfaces: [ Ethernet1, Ethernet6 ]
  node_groups:
    - group: RACK1
      filter:
        tags: [ "DB" ]
      nodes:
        - name: s2-leaf1
          id: 1
          mgmt_ip: 192.168.0.22/24
          uplink_switch_interfaces: [ Ethernet2, Ethernet2 ]
        - name: s2-leaf2
          id: 2
          mgmt_ip: 192.168.0.23/24
          uplink_switch_interfaces: [ Ethernet3, Ethernet3 ]
    - group: RACK2
      filter:
        tags: [ "DMZ" ]
      nodes:
        - name: s2-leaf3
          id: 3
          mgmt_ip: 192.168.0.24/24
          uplink_switch_interfaces: [ Ethernet4, Ethernet4 ]
        - name: s2-leaf4
          id: 4
          mgmt_ip: 192.168.0.25/24
          uplink_switch_interfaces: [ Ethernet5, Ethernet5 ]
